### ISSUE TITLE
MacOS installation issues

### ISSUE THREAD

**Issue by akazachk** [ANL-CEEESA/MIPLearn#2]
On MacOS 10.15.6 with python 3.8.5 installed via brew, changing [line 18](https://github.com/ANL-CEEESA/MIPLearn/blob/9c816badfb91e6d8d75cb520d728b9d03e716bcc/Makefile#L18) in the Makefile to
```
cd src/python && python3 setup.py install
```
then `make install` is seemingly successful (except the Julia installation error).

However, in python3, I have an error loading miplearn:

```
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import miplearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/miplearn-0.1-py3.8.egg/miplearn/__init__.py", line 10, in <module>
ModuleNotFoundError: No module named 'miplearn.components'
```

The same issue does not happen when using `make develop`.

**Comment by iSoron** [comment]
Thanks @akazachk. This should be fixed in 261cb89a4da7d42988db65cb27083c587ed5a48e. If it's not, please let me know.
